package: bokeh

platform:
  - linux-64

engine:
   - python=2

before_script:
  - python -V

script: |
  conda build conda.recipe;
  mkdir -p dist_osx dist_win;
  mkdir -p /opt/anaconda/conda-bld/win-64 /opt/anaconda/conda-bld/osx-64 ;
  conda convert -o dist_win -p win-64 -f /opt/anaconda/conda-bld/linux-64/bokeh*.tar.bz2;
  filename=`ls dist_win/bokeh*.tar.bz2 | xargs -n 1 basename`;
  echo $filename;
  cp -r dist_win/$filename /opt/anaconda/conda-bld/win-64/$filename;
  conda convert -o dist_osx -p osx-64 -f /opt/anaconda/conda-bld/linux-64/bokeh*.tar.bz2;
  filename=`ls dist_osx/bokeh*.tar.bz2 | xargs -n 1 basename`;
  echo $filename
  cp -r dist_osx/$filename /opt/anaconda/conda-bld/osx-64/$filename;

build_targets:
    files: /opt/anaconda/conda-bld/*/bokeh*.tar.bz2
    channels: 'nightly'

